# This is a basic workflow to help you get started with Actions

name: TestTrig
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: 🛎 Check out main
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.MAIN_BIN_PATH }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
      - name: make dir set bin
        run: |
          mkdir TB1_REPO
          7z  x -p${{ secrets.MAIN_BIN_ZIP_PASS }} bin.7z.001
          ren TB1_MAIN_TEMP TB1_MAIN
      - name: debug dir
        run: |
          cd TB1_MAIN
          ls

      - name: ZZ
        run: |
          cd TB1_MAIN\999_programs\GithubActionsHelper
          java -Xms128m -Xmx4g -jar GithubActionsHelperMain.jar Sleep 1000
      - name: TRI
        run: |
          cd TB1_MAIN\999_programs\GithubActionsHelper
          java -Xms128m -Xmx4g -jar GithubActionsHelperMain.jar ${{ secrets.TRI_TB1_NT_AD }}
